INSERT INTO exercises(sentence, answer)
VALUES ('I __ (listen) to the radio while Mary __ (cook) dinner.', 'was listening, was cooking'),
       ('__ (you buy) this book yesterday?', 'did you buy'),
       ('Last Friday Jill __ (go) home early because she __ (want) to see a film.', 'went, wanted'),
       ('When __ (your brother usually get) home in the evening?', 'does your brother usually get'),
       ('Jane always __ (bring) us a nice present.', 'brings'),
       ('What those __ (people do) in the middle of the road?', 'are people doing'),
       ('__ (you read) this book?', 'have you read'),
       ('While Fred __ (sleep), Judy __ (watch) TV.', 'was sleeping, was watching'),
       ('When I __ (be) young, I __ (think) Mary __ (be) nice — but now I __ (think) she’s fantastic.', 'was, thought, was, think'),
       ('Jill __ (walk) home when she __ (see) her husband’s car outside the cinema', 'was walking, saw'),
       ('Look there! Sue and Tim __ (run) to school.', 'are running'),
       ('Jack’s father __ (not work) in London — he __ (not speak) English.', 'doesn`t work, doesn`t speak'),
       ('Joe __ (buy) a car yesterday.', 'bought'),
       ('Their father often __ (go) to rock concerts.', 'goes'),
       ('While you __ (sleep), mother __ (arrive).', 'were sleeping , arrived.'),
       ('Alice __ (not to take) the bus to school every day. She usually __ (to walk) to school__', 'doesn`t take, walks'),
       ('(to take) __ you the bus to get to school or __ (to walk you)?', 'Do you take, Do you walk'),
       ('Who is this man? I __ (to think) that I __ (to know) him, but I __ (to forget) his name.', 'think, know, have forgotten'),
       ('The children __ (to have) a good time in the park yesterday. They __ (to give) small pieces of bread to the ducks. Then they __ (to take) pictures of themselves.', 'had, gave,took'),
       ('Where are the children? They __ (to watch) TV in the room now. Some minutes ago they __ (to play) a game.', 'are watching, were playing'),
       ('Now I am in my class. I__ (to sit) at my desk. I always __ (to sit) at the same desk.', 'am sitting, sit'),
       ('When __ (you know) your examination results?', 'will you know'),
       ('Kathy__ (travel) to Caracas next month to attend a conference.', 'is travelling'),
       ('Do you have any plans for lunch today? — I __ (meet) Shannon at the Sham Cafe in an hour. Do you want to join us?', 'am meeting'),
       ('I __ (buy) a bicycle for my son for his birthday next month. Do you know anything about bikes for kids? — Sure. What do you want to know?', 'am going to buy'),
       ('How do you like your new job? — I don’t start it until tomorrow. I__ (give) you an answer next week.', 'will give'),
       ('I suppose he__ (talk) about his new invention.', 'is going to talk'),
       ('Why are you packing your suitcase? — I __ (leave) for Los Angeles in a couple of hours.', 'am leaving'),
       ('My regular doctor, Dr. Jordan, __ (attend) a conference in Las Vegas next week, so I hope I __ (meet) her partner, Dr. Peterson, when I __ (go) for my appointment next Friday.', 'is attending, will meet, go'),
       ('What time __ (class begin) tomorrow morning? — It__ (begin) at eight o’clock sharp.', 'does class begin, begins'),
       ('The coffee shop __ (open) at seven o’clock tomorrow morning. I’ll meet you there at 7:15. — Okay. I’ll be there.', 'opens'),
       ('At 5 o’clock tomorrow he __ (work).', 'will be working'),
       ('He can’t come at noon tomorrow because he __ (give) a lesson at that time.', 'will be giving'),
       ('She__ (read) an interesting book the whole evening tomorrow.', 'will be reading'),
       ('At 10 o’clock tomorrow morning he__ (talk) to his friend.', 'will be talking'),
       ('You will recognize her when you see her. She __ (wear) a yellow hat.', 'will be wearing'),
       ('He__ (have a party) on Saturday 4th December in London at 10 pm.', 'will be having'),
       ('In the next days you __ (visit) famous sights.', 'will visit'),
       ('Jeanne and Paul__ (move) to London next month.', 'are moving'),
       ('Leave the washing up. - I __ (do) it later.', 'will do'),
       ('This time tomorrow I __ (lie) on the beach.', 'will be lying'),
       ('Look out! You __ (spill) your tea!', 'will spill'),
       ('Aren’t you about to finish with the dishes? You __ (wash) the dishes for thirty minutes or more. How long can it take you to wash the dishes?', 'have been washing'),
       ('We __ (go) to the Steak House restaurant many times. The food is excellent.', 'have gone'),
       ('A: What is that sound?\nB: A car alarm __ (ring) somewhere down the street. It __ (drive) me crazy — I wish it would stop! It __ (ring) for more than twenty minutes.', 'is ringing, is driving, has been ringing'),
       ('Can you translate this note from Stockholm? I understood Swedish when I __ (be) a child, but I __ (forget) it all.', 'was, have forgotten'),
       ('What’s that dent in the side of the car? __ (you have) an accident?', 'have you had'),
       ('I’m sorry, John’s not here; he __ (go) to the dentist. He __ (have) trouble with a tooth for some time.', 'has gone, has had'),
       ('This cassette recorder is broken. __ (you play) about with it?', 'have you played'),
       ('Your Italian is very good. __ (you study) it long?', 'have you been studying'),
       ('Do you mind if I clear the table? __ (you have) enough to eat?', 'have you had'),
       ('Ann never __ (go) camping. She __ (not sleep) in a tent.', 'has never gone, has never slept'),
       ('Frank, where have you been? We __ (wait) for you since 1 p.m.', 'have been waiting'),
       ('I’m not surprised he __ (fail) that exam. He __ (not work) hard recently.', 'has failed, hasn`t been working'),
       ('Oh no! The children __ (cook). Look at the state of this kitchen!', 'have been cooking'),
       ('How many times __ (Wendy be) late for work this week?', 'has Wendy been'),
       ('I’m going to give that cat some food. It __ (sit) on the doorstep for hours. I’m sure it’s starving.', 'has been sitting'),
       ('I __ (do) grammar exercises all morning. I deserve a treat for lunch.', 'have been doing'),
       ('__ (You not buy) your mother a present? That’s really mean of you.', 'haven’t you bought'),
       ('She __ (work) in Australia for 2 years. Then she moved.', 'worked'),
       ('Now where are my keys? This is the third time I __ (lose) them today', 'have lost'),
       ('__ (you ever play) chess? You should try it. I’m sure it’s the sort that you’d like.', 'have you ever played'),
       ('Oh do be quiet. You __ (grumble) all day!', 'have been grumbling'),
       ('Your tennis __ (really improve)! __ (you practice) in secret?', 'has really improved, have you practiced'),
       ('It’s only the middle of the month, and he__ (spend) (already) most of his salary; he __ (spend) $60 yesterday,', 'have already worked'),
       ('I __ (break) my leg in 1991, but I __ (break) (never) my arm.', 'broke , have never broken'),
       ('He’s over sixty, and he’s still working. He __ (work) hard all his life. When he __ (be) a young man, he sometimes __ (work) all night.', 'has been working hard, wa, worked'),
       ('The postman __ (come) at eight yesterday, but it’s now half past eight and he __ (not come) yet.', 'came, hasn`t come'),
       ('Today is May 25th. Ted __ (not be) absent this month.', 'hasn`t been'),
       ('He __ (feel) extremely ill when he went to hospital, but he __ (feel) much better since he came out of hospital a month ago.', 'felt, has felt')